  name: CI
  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v11
      - name: Run tests
        run: sbt test